-- Creating schema for IDENTITY subdomain
DROP SCHEMA IF EXISTS IDENTITY CASCADE;
Create SCHEMA IDENTITY;

-- User model
DROP TABLE IF EXISTS IDENTITY.USER;
CREATE TABLE IDENTITY.USER (
	ID               VARCHAR,
	EMAIL            VARCHAR UNIQUE,
	HASHPASSWORD     VARCHAR
);