version: "3.6"
services:
  productfinder-db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - productfinder-data:/var/lib/postgresql/data
      - ./db/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    env_file:
      - ./db/test.env
volumes:
  productfinder-data:
